USE HosPetAll;
insert into race (name) values
  ('Dog'),
  ('Cat'),
  ('Mouse'),
  ('Duck'),
  ('Rabbit'),
  ('Admiral, indian red'),
  ('African black crake'),
  ('African bush squirrel'),
  ('African fish eagle'),
  ('African ground squirrel (unidentified)'),
  ('African lynx'),
  ('African red-eyed bulbul'),
  ('African snake (unidentified)'),
  ('African wild cat'),
  ('African wild dog'),
  ('Agouti'),
  ('Albatross, galapagos'),
  ('Albatross, waved'),
  ('Alligator, american'),
  ('Alligator, mississippi'),
  ('American Virginia opossum'),
  ('American alligator'),
  ('American badger'),
  ('American beaver'),
  ('American bighorn sheep'),
  ('American buffalo'),
  ('American racer'),
  ('Anaconda (unidentified)'),
  ('Anteater, giant'),
  ('Antechinus, brown'),
  ('Antelope ground squirrel'),
  ('Antelope, roan'),
  ('Arboral spiny rat'),
  ('Arctic fox'),
  ('Arctic hare'),
  ('Arctic tern'),
  ('Argalis'),
  ('Armadillo, nine-banded'),
  ('Armadillo, seven-banded'),
  ('Asian elephant'),
  ('Asian false vampire bat'),
  ('Asian lion'),
  ('Asian red fox'),
  ('Asian water buffalo'),
  ('Asian water dragon'),
  ('Asiatic wild ass'),
  ('Australian masked owl'),
  ('Australian spiny anteater'),
  ('Avocet, pied'),
  ('Baboon, yellow'),
  ('Badger, european'),
  ('Bahama pintail'),
  ('Banded mongoose'),
  ('Bandicoot, short-nosed'),
  ('Barasingha deer'),
  ('Barbet, black-collared'),
  ('Bare-faced go away bird'),
  ('Barrows goldeneye'),
  ('Bat, asian false vampire'),
  ('Bat, little brown'),
  ('Beaver, american'),
  ('Beaver, eurasian'),
  ('Beaver, european'),
  ('Beaver, north american'),
  ('Bee-eater (unidentified)'),
  ('Beisa oryx'),
  ('Bengal vulture'),
  ('Bent-toed gecko'),
  ('Bettong, brush-tailed'),
  ('Bird (unidentified)'),
  ('Bird, magnificent frigate'),
  ('Bird, pied butcher'),
  ('Bird, secretary'),
  ('Black bear'),
  ('Black curlew'),
  ('Black rhinoceros'),
  ('Black spider monkey'),
  ('Black swan'),
  ('Black-backed magpie'),
  ('Black-capped capuchin'),
  ('Black-capped chickadee'),
  ('Black-collared barbet'),
  ('Black-crowned crane'),
  ('Black-crowned night heron'),
  ('Black-eyed bulbul'),
  ('Black-faced kangaroo'),
  ('Black-tailed deer'),
  ('Black-tailed tree creeper'),
  ('Blackbird, red-winged'),
  ('Bleu, blue-breasted cordon'),
  ('Bleu, red-cheeked cordon'),
  ('Blue and yellow macaw'),
  ('Blue catfish'),
  ('Blue crane'),
  ('Blue peacock'),
  ('Blue wildebeest'),
  ('Blue-breasted cordon bleu'),
  ('Blue-footed booby'),
  ('Blue-tongued skink'),
  ('Boa, columbian rainbow'),
  ('Boa, malagasy ground'),
  ('Boa, mexican'),
  ('Boar, wild'),
  ('Boat-billed heron'),
  ('Bobcat'),
  ('Bohor reedbuck'),
  ('Bonnet macaque'),
  ('Bontebok'),
  ('Booby, masked'),
  ('Bottle-nose dolphin'),
  ('Boubou, southern'),
  ('Brazilian otter'),
  ('Brazilian tapir'),
  ('Brindled gnu'),
  ('Brocket, red'),
  ('Brolga crane'),
  ('Brown brocket'),
  ('Brown hyena'),
  ('Brown pelican'),
  ('Brush-tailed rat kangaroo'),
  ('Buffalo, african'),
  ('Buffalo, wild water'),
  ('Bulbul, black-eyed'),
  ('Burmese brown mountain tortoise'),
  ('Bush dog'),
  ('Bushbaby, large-eared'),
  ('Bushpig'),
  ('Bustard, kori'),
  ('Bustard, stanley'),
  ('Buttermilk snake'),
  ('California sea lion'),
  ('Camel, dromedary'),
  ('Canadian tiger swallowtail butterfly'),
  ('Cape clawless otter'),
  ('Cape raven'),
  ('Cape white-eye'),
  ('Cape wild cat'),
  ('Capuchin, black-capped'),
  ('Capuchin, brown'),
  ('Caracara (unidentified)'),
  ('Cardinal, black-throated'),
  ('Cardinal, red-capped'),
  ('Caribou'),
  ('Carpet python'),
  ('Cat, civet'),
  ('Cat, european wild'),
  ('Cat, jungle'),
  ('Cat, kaffir'),
  ('Cat, miner''s'),
  ('Cat, native'),
  ('Cat, ringtail'),
  ('Cat, tiger'),
  ('Cat, toddy'),
  ('Cattle egret'),
  ('Chacma baboon'),
  ('Chameleon (unidentified)'),
  ('Chestnut weaver'),
  ('Chipmunk, least'),
  ('Civet, common palm'),
  ('Civet, small-toothed palm'),
  ('Cliffchat, mocking'),
  ('Coatimundi, white-nosed'),
  ('Cobra (unidentified)'),
  ('Cockatoo, long-billed'),
  ('Cockatoo, red-tailed'),
  ('Cockatoo, roseate'),
  ('Cockatoo, sulfur-crested'),
  ('Collared lemming'),
  ('Collared peccary'),
  ('Common brushtail possum'),
  ('Common duiker'),
  ('Common eland'),
  ('Common grenadier'),
  ('Common long-nosed armadillo'),
  ('Common melba finch'),
  ('Common nighthawk'),
  ('Common pheasant'),
  ('Common rhea'),
  ('Common shelduck'),
  ('Common turkey'),
  ('Common wallaroo'),
  ('Common wombat'),
  ('Common zebra'),
  ('Coot, red-knobbed'),
  ('Corella, long-billed'),
  ('Cormorant, flightless'),
  ('Cormorant, great'),
  ('Cormorant, javanese'),
  ('Cormorant, king'),
  ('Cormorant, large'),
  ('Cormorant, little'),
  ('Cottonmouth'),
  ('Cougar'),
  ('Crab-eating fox'),
  ('Crake, african black'),
  ('Crane, black-crowned'),
  ('Crane, brolga'),
  ('Crane, sandhill'),
  ('Crane, stanley'),
  ('Crane, wattled'),
  ('Creeper, black-tailed tree'),
  ('Crested barbet'),
  ('Crested porcupine'),
  ('Crested screamer'),
  ('Crow, american'),
  ('Crow, house'),
  ('Crow, pied'),
  ('Crowned eagle'),
  ('Cuis'),
  ('Curlew, black'),
  ('Currasow (unidentified)'),
  ('Dabchick'),
  ('Dark-winged trumpeter'),
  ('Darwin ground finch (unidentified)'),
  ('Deer, red'),
  ('Deer, spotted'),
  ('Deer, swamp'),
  ('Deer, white-tailed'),
  ('Desert tortoise'),
  ('Devil, tasmanian'),
  ('Dingo'),
  ('Dog, bush'),
  ('Dolphin, bottle-nose'),
  ('Dove, laughing'),
  ('Dove, little brown'),
  ('Dove, mourning collared'),
  ('Dragon, asian water'),
  ('Dragon, komodo'),
  ('Dragon, ornate rock'),
  ('Dragonfly, russian'),
  ('Dromedary camel'),
  ('Duck, blue'),
  ('Duiker, gray'),
  ('Dunnart, fat-tailed'),
  ('Eagle owl (unidentified)'),
  ('Eagle, bald'),
  ('Eagle, bateleur'),
  ('Eagle, crowned'),
  ('Eagle, golden'),
  ('Eagle, pallas''s fish'),
  ('Eastern box turtle'),
  ('Eastern cottontail rabbit'),
  ('Eastern dwarf mongoose'),
  ('Eastern indigo snake'),
  ('Eastern quoll'),
  ('Echidna, short-beaked'),
  ('Egyptian viper'),
  ('Egyptian vulture'),
  ('Elephant, african'),
  ('Elephant, asian'),
  ('Emerald green tree boa'),
  ('Eurasian badger'),
  ('Eurasian hoopoe'),
  ('European badger'),
  ('European beaver'),
  ('European red squirrel'),
  ('European shelduck'),
  ('European wild cat'),
  ('Falcon, peregrine'),
  ('Falcon, prairie'),
  ('Fat-tailed dunnart'),
  ('Feral rock pigeon'),
  ('Flamingo, chilean'),
  ('Flicker, campo'),
  ('Flightless cormorant'),
  ('Flycatcher, tyrant'),
  ('Flying fox (unidentified)'),
  ('Fork-tailed drongo'),
  ('Four-horned antelope'),
  ('Four-spotted skimmer'),
  ('Fox, cape'),
  ('Fox, grey'),
  ('Fox, north american red'),
  ('Frilled lizard'),
  ('Frog (unidentified)'),
  ('Frogmouth, tawny'),
  ('Galah'),
  ('Galapagos mockingbird'),
  ('Galapagos tortoise'),
  ('Gazelle, grant''s'),
  ('Gazelle, thomson''s'),
  ('Gazer, sun'),
  ('Gecko (unidentified)'),
  ('Gecko, barking'),
  ('Gemsbok'),
  ('Gila monster'),
  ('Giraffe'),
  ('Glider, feathertail'),
  ('Glossy ibis'),
  ('Glossy starling (unidentified)'),
  ('Goanna lizard'),
  ('Golden brush-tailed possum'),
  ('Golden jackal'),
  ('Golden-mantled ground squirrel'),
  ('Goldeneye, barrows'),
  ('Goldeneye, common'),
  ('Goliath heron'),
  ('Goose, andean'),
  ('Goose, canada'),
  ('Goose, greylag'),
  ('Goose, snow'),
  ('Goose, spur-winged'),
  ('Gorilla, western lowland'),
  ('Grant''s gazelle'),
  ('Gray duiker'),
  ('Gray rhea'),
  ('Great egret'),
  ('Great horned owl'),
  ('Great kiskadee'),
  ('Greater blue-eared starling'),
  ('Greater roadrunner'),
  ('Green vine snake'),
  ('Green-backed heron'),
  ('Green-winged macaw'),
  ('Grey fox'),
  ('Grey heron'),
  ('Grey mouse lemur'),
  ('Grey-footed squirrel'),
  ('Greylag goose'),
  ('Griffon vulture'),
  ('Grizzly bear'),
  ('Ground legaan'),
  ('Gull, kelp'),
  ('Gull, silver'),
  ('Gull, swallow-tail'),
  ('Hanuman langur'),
  ('Harbor seal'),
  ('Hartebeest, coke''s'),
  ('Hawk, galapagos'),
  ('Hawk-eagle, crowned'),
  ('Hawk-headed parrot'),
  ('Heron, black-crowned night'),
  ('Heron, boat-billed'),
  ('Heron, goliath'),
  ('Heron, gray'),
  ('Heron, grey'),
  ('Heron, striated'),
  ('Hoary marmot'),
  ('Hornbill, leadbeateri''s ground'),
  ('Hornbill, red-billed'),
  ('Horned lark'),
  ('Horned puffin'),
  ('Horned rattlesnake'),
  ('Hottentot teal'),
  ('Hudsonian godwit'),
  ('Hummingbird (unidentified)'),
  ('Huron'),
  ('Hyena, brown'),
  ('Hyena, spotted'),
  ('Hyrax'),
  ('Ibis, glossy'),
  ('Ibis, puna'),
  ('Ibis, sacred'),
  ('Iguana, marine'),
  ('Impala'),
  ('Indian giant squirrel'),
  ('Indian peacock'),
  ('Indian red admiral'),
  ('Indian tree pie'),
  ('Insect, stick'),
  ('Jackal, black-backed'),
  ('Jackal, golden'),
  ('Jackal, indian'),
  ('Jackal, silver-backed'),
  ('Jaeger, long-tailed'),
  ('Jaguar'),
  ('Jaguarundi'),
  ('Javan gold-spotted mongoose'),
  ('Javanese cormorant'),
  ('Jungle cat'),
  ('Jungle kangaroo'),
  ('Kafue flats lechwe'),
  ('Kangaroo, eastern grey'),
  ('Kangaroo, jungle'),
  ('Kingfisher, malachite'),
  ('Kingfisher, pied'),
  ('Kite, black'),
  ('Klipspringer'),
  ('Komodo dragon'),
  ('Kori bustard'),
  ('Land iguana'),
  ('Langur, gray'),
  ('Langur, hanuman'),
  ('Lappet-faced vulture'),
  ('Lapwing, southern'),
  ('Laughing dove'),
  ('Lava gull'),
  ('Least chipmunk'),
  ('Legaan, Monitor (unidentified)'),
  ('Lemming, arctic'),
  ('Lemur, brown'),
  ('Lemur, grey mouse'),
  ('Lemur, lesser mouse'),
  ('Lemur, ring-tailed'),
  ('Leopard'),
  ('Lesser double-collared sunbird'),
  ('Lesser masked weaver'),
  ('Levaillant''s barbet'),
  ('Lilac-breasted roller'),
  ('Lion, african'),
  ('Lion, australian sea'),
  ('Lion, california sea'),
  ('Lion, mountain'),
  ('Lion, south american sea'),
  ('Little blue penguin'),
  ('Little brown bat'),
  ('Little brown dove'),
  ('Little cormorant'),
  ('Little grebe'),
  ('Little heron'),
  ('Lizard (unidentified)'),
  ('Lizard, desert spiny'),
  ('Lizard, frilled'),
  ('Long-billed cockatoo'),
  ('Long-billed corella'),
  ('Long-crested hawk eagle'),
  ('Long-necked turtle'),
  ('Long-tailed jaeger'),
  ('Long-tailed spotted cat'),
  ('Lorikeet, scaly-breasted'),
  ('Loris, slender'),
  ('Lynx, african'),
  ('Macaque, bonnet'),
  ('Macaque, rhesus'),
  ('Macaw, blue and gold'),
  ('Macaw, blue and gold'),
  ('Macaw, green-winged'),
  ('Macaw, red and blue'),
  ('Macaw, scarlet'),
  ('Madagascar hawk owl'),
  ('Magellanic penguin'),
  ('Magistrate black colobus'),
  ('Magnificent frigate bird'),
  ('Magpie, australian'),
  ('Magpie, black-backed'),
  ('Malabar squirrel'),
  ('Malachite kingfisher'),
  ('Malleefowl'),
  ('Mandras tree shrew'),
  ('Marmot, hoary'),
  ('Marmot, yellow-bellied'),
  ('Masked booby'),
  ('Mexican boa'),
  ('Mexican wolf'),
  ('Miner''s cat'),
  ('Moccasin, water'),
  ('Mocking cliffchat'),
  ('Mongoose, eastern dwarf'),
  ('Monkey, black spider'),
  ('Monkey, bleeding heart'),
  ('Monkey, red howler'),
  ('Monkey, rhesus'),
  ('Monkey, vervet'),
  ('Moose'),
  ('Mountain lion'),
  ('Mourning collared dove'),
  ('Mouse, four-striped grass'),
  ('Musk ox'),
  ('Mynah, indian'),
  ('Neotropic cormorant'),
  ('Netted rock dragon'),
  ('Nilgai'),
  ('North American porcupine'),
  ('Northern fur seal'),
  ('Northern phalarope'),
  ('Nutcracker, clark''s'),
  ('Olive baboon'),
  ('Onager'),
  ('Openbill stork'),
  ('Openbill, asian'),
  ('Opossum, american virginia'),
  ('Orca'),
  ('Oribi'),
  ('Oriental short-clawed otter'),
  ('Oryx, fringe-eared'),
  ('Ostrich'),
  ('Otter, brazilian'),
  ('Otter, canadian river'),
  ('Otter, cape clawless'),
  ('Otter, giant'),
  ('Otter, north american river'),
  ('Otter, oriental short-clawed'),
  ('Ovenbird'),
  ('Owl, madagascar hawk'),
  ('Owl, snowy'),
  ('Owl, white-browed'),
  ('Pacific gull'),
  ('Paddy heron (unidentified)'),
  ('Pademelon, red-legged'),
  ('Pale-throated three-toed sloth'),
  ('Palm squirrel'),
  ('Pampa gray fox'),
  ('Parakeet, rose-ringed'),
  ('Parrot, hawk-headed'),
  ('Peacock, blue'),
  ('Pelican, australian'),
  ('Penguin, fairy'),
  ('Penguin, galapagos'),
  ('Penguin, little blue'),
  ('Penguin, magellanic'),
  ('Phalarope, northern'),
  ('Phalarope, red-necked'),
  ('Phascogale, brush-tailed'),
  ('Phascogale, red-tailed'),
  ('Pheasant, common'),
  ('Pie, rufous tree'),
  ('Pied butcher bird'),
  ('Pied crow'),
  ('Pied kingfisher'),
  ('Pigeon, feral rock'),
  ('Pine siskin'),
  ('Pine snake (unidentified)'),
  ('Pintail, bahama'),
  ('Pintail, white-cheeked'),
  ('Platypus'),
  ('Plover, three-banded'),
  ('Pocket gopher (unidentified)'),
  ('Polecat, african'),
  ('Porcupine, prehensile-tailed'),
  ('Possum, common brushtail'),
  ('Possum, golden brush-tailed'),
  ('Possum, western pygmy'),
  ('Pronghorn'),
  ('Puna ibis'),
  ('Purple grenadier'),
  ('Purple moorhen'),
  ('Python (unidentified)'),
  ('Quoll, spotted-tailed'),
  ('Raccoon, crab-eating'),
  ('Racer snake'),
  ('Racer, blue'),
  ('Rat, desert kangaroo'),
  ('Rattlesnake, dusky'),
  ('Rattlesnake, eastern diamondback'),
  ('Raven, cape'),
  ('Red and blue macaw'),
  ('Red brocket'),
  ('Red deer'),
  ('Red lava crab'),
  ('Red phalarope'),
  ('Red-billed buffalo weaver'),
  ('Red-breasted nuthatch'),
  ('Red-capped cardinal'),
  ('Red-cheeked cordon bleu'),
  ('Red-legged pademelon'),
  ('Red-necked phalarope'),
  ('Red-necked wallaby'),
  ('Red-shouldered glossy starling'),
  ('Red-tailed phascogale'),
  ('Red-tailed wambenger'),
  ('Red-winged blackbird'),
  ('Red-winged hawk (unidentified)'),
  ('Reedbuck, bohor'),
  ('Rhea, greater'),
  ('Rhesus macaque'),
  ('Rhinoceros, square-lipped'),
  ('Rhinoceros, white'),
  ('Ring dove'),
  ('Ring-necked pheasant'),
  ('Ring-tailed lemur'),
  ('Ringtail'),
  ('Roadrunner, greater'),
  ('Roan antelope'),
  ('Robin, kalahari scrub'),
  ('Roseat flamingo'),
  ('Rufous tree pie'),
  ('Rufous-collared sparrow'),
  ('Russian dragonfly'),
  ('Sable antelope'),
  ('Sage grouse'),
  ('Sally lightfoot crab'),
  ('Salmon pink bird eater tarantula'),
  ('Salmon, sockeye'),
  ('Sambar'),
  ('Savanna baboon'),
  ('Savanna fox'),
  ('Savannah deer (unidentified)'),
  ('Screamer, crested'),
  ('Screamer, southern'),
  ('Seal, common'),
  ('Seal, northern elephant'),
  ('Seal, northern fur'),
  ('Serval'),
  ('Seven-banded armadillo'),
  ('Sheep, american bighorn'),
  ('Sheep, red'),
  ('Sheep, stone'),
  ('Shelduck, common'),
  ('Short-nosed bandicoot'),
  ('Shrew, mandras tree'),
  ('Shrike, crimson-breasted'),
  ('Silver-backed fox'),
  ('Siskin, yellow-rumped'),
  ('Skink, blue-tongued'),
  ('Skua, great'),
  ('Slender loris'),
  ('Sloth bear'),
  ('Sloth, pale-throated three-toed'),
  ('Sloth, two-toed'),
  ('Small-clawed otter'),
  ('Small-spotted genet'),
  ('Small-toothed palm civet'),
  ('Snake, buttermilk'),
  ('Snake-necked turtle'),
  ('Snowy sheathbill'),
  ('Sociable weaver'),
  ('Sockeye salmon'),
  ('South American meadowlark (unidentified)'),
  ('South American puma'),
  ('South American sea lion'),
  ('Southern black-backed gull'),
  ('Southern boubou'),
  ('Southern hairy-nosed wombat'),
  ('Southern screamer'),
  ('Southern white-crowned shrike'),
  ('Sparrow, rufous-collared'),
  ('Spider, wolf'),
  ('Spotted hyena'),
  ('Spotted wood sandpiper'),
  ('Springhare'),
  ('Spurfowl, yellow-necked'),
  ('Square-lipped rhinoceros'),
  ('Squirrel, eastern fox'),
  ('Squirrel, malabar'),
  ('Squirrel, nelson ground'),
  ('Squirrel, palm'),
  ('Squirrel, red'),
  ('Squirrel, thirteen-lined'),
  ('Starling, greater blue-eared'),
  ('Starling, red-shouldered glossy'),
  ('Starling, superb'),
  ('Steenbok'),
  ('Stick insect'),
  ('Stilt, black-winged'),
  ('Stone sheep'),
  ('Stork, black-necked'),
  ('Stork, european'),
  ('Stork, greater adjutant'),
  ('Stork, marabou'),
  ('Stork, openbill'),
  ('Stork, white'),
  ('Stork, yellow-billed'),
  ('Striped hyena'),
  ('Striped skunk'),
  ('Sugar glider'),
  ('Sun gazer'),
  ('Sunbird, lesser double-collared'),
  ('Superb starling'),
  ('Suricate'),
  ('Swallow-tail gull'),
  ('Swan, trumpeter'),
  ('Tailless tenrec'),
  ('Tammar wallaby'),
  ('Tarantula'),
  ('Tawny frogmouth'),
  ('Teal, hottentot'),
  ('Tenrec, tailless'),
  ('Three-banded plover'),
  ('Tiger snake'),
  ('Timber wolf'),
  ('Toddy cat'),
  ('Topi'),
  ('Tortoise, burmese brown mountain'),
  ('Tortoise, desert'),
  ('Tortoise, galapagos'),
  ('Tropical buckeye butterfly'),
  ('Trotter, lily'),
  ('Trumpeter, green-winged'),
  ('Tsessebe'),
  ('Turkey, common'),
  ('Turtle (unidentified)'),
  ('Two-toed sloth'),
  ('Urial'),
  ('Verreaux''s sifaka'),
  ('Vulture, bengal'),
  ('Vulture, egyptian'),
  ('Vulture, oriental white-backed'),
  ('Vulture, turkey'),
  ('Vulture, white-rumped'),
  ('Wallaby, agile'),
  ('Wallaby, bennett''s'),
  ('Wallaby, dama'),
  ('Wallaby, river'),
  ('Wallaby, tammar'),
  ('Wallaby, whip-tailed'),
  ('Warthog'),
  ('Waterbuck, common'),
  ('Waterbuck, defassa'),
  ('Wattled crane'),
  ('Weaver, chestnut'),
  ('Weaver, lesser masked'),
  ('Weaver, sociable'),
  ('Western bearded dragon'),
  ('Western palm tanager (unidentified)'),
  ('Western pygmy possum'),
  ('Western spotted skunk'),
  ('White rhinoceros'),
  ('White-browed sparrow weaver'),
  ('White-faced whistling duck'),
  ('White-fronted bee-eater'),
  ('White-fronted capuchin'),
  ('White-headed vulture'),
  ('White-lipped peccary'),
  ('White-mantled colobus'),
  ('White-necked stork'),
  ('White-nosed coatimundi'),
  ('White-tailed jackrabbit'),
  ('White-throated robin'),
  ('White-throated toucan'),
  ('White-winged tern'),
  ('Wild turkey'),
  ('Wild water buffalo'),
  ('Wildebeest, blue'),
  ('Wolf spider'),
  ('Wolf, common'),
  ('Wolf, timber'),
  ('Wombat, common'),
  ('Woodchuck'),
  ('Woodcock, american'),
  ('Woodrat (unidentified)'),
  ('Woylie'),
  ('Yak'),
  ('Yellow-bellied marmot'),
  ('Yellow-billed hornbill'),
  ('Yellow-crowned night heron'),
  ('Zebra, common'),
  ('Zebra, plains'),
  ('Zorilla')
