USE HosPetAll;
insert into race (name) values ('Blue wildebeest'); 
insert into race (name) values ('Sally lightfoot crab');
insert into race (name) values ('Loris, slender');
insert into race (name) values ('Hyena, spotted');
insert into race (name) values ('Gray rhea');
insert into race (name) values ('Swainson''s francolin');
insert into race (name) values ('Superb starling');
insert into race (name) values ('Common duiker');
insert into race (name) values ('European badger');
insert into race (name) values ('Lion, mountain');
insert into race (name) values ('Otter, giant');
insert into race (name) values ('Red deer');
insert into race (name) values ('Harbor seal');
insert into race (name) values ('Spurfowl, yellow-necked');
insert into race (name) values ('Clark''s nutcracker');
insert into race (name) values ('Lion, australian sea');
insert into race (name) values ('Northern phalarope');
insert into race (name) values ('Hawk, galapagos');
insert into race (name) values ('Trumpeter, green-winged');
insert into race (name) values ('Cat, jungle');
insert into race (name) values ('Moose');
insert into race (name) values ('Golden jackal');
insert into race (name) values ('Pied butcher bird');
insert into race (name) values ('Serval');
insert into race (name) values ('Jungle cat');
insert into race (name) values ('Javanese cormorant');
insert into race (name) values ('Black curlew');
insert into race (name) values ('Palm squirrel');
insert into race (name) values ('Laughing dove');
insert into race (name) values ('Wallaby, agile');
insert into race (name) values ('Hottentot teal');
insert into race (name) values ('Arctic tern');
insert into race (name) values ('Crane, black-crowned');
insert into race (name) values ('Crane, sandhill');
insert into race (name) values ('Little brown dove');
insert into race (name) values ('Otter, brazilian');
insert into race (name) values ('Pintail, bahama');
insert into race (name) values ('Ground legaan');
insert into race (name) values ('White-necked stork');
insert into race (name) values ('Tenrec, tailless');
insert into race (name) values ('Elephant, asian');
insert into race (name) values ('Wolf, common');
insert into race (name) values ('Salmon, sockeye');
insert into race (name) values ('Oryx, fringe-eared');
insert into race (name) values ('Hornbill, leadbeateri''s ground');
insert into race (name) values ('Magellanic penguin');
insert into race (name) values ('Cattle egret');
insert into race (name) values ('Cockatoo, red-tailed');
insert into race (name) values ('Hornbill, red-billed');
insert into race (name) values ('Pocket gopher (unidentified)');
insert into race (name) values ('Moccasin, water');
insert into race (name) values ('Boa, mexican');
insert into race (name) values ('Goanna lizard');
insert into race (name) values ('Red-capped cardinal');
insert into race (name) values ('Armadillo, seven-banded');
insert into race (name) values ('Common turkey');
insert into race (name) values ('Desert tortoise');
insert into race (name) values ('American racer');
insert into race (name) values ('Blue-tongued skink');
insert into race (name) values ('Deer, red');
insert into race (name) values ('Warthog');
insert into race (name) values ('Little blue penguin');
insert into race (name) values ('Rufous tree pie');
insert into race (name) values ('American Virginia opossum');
insert into race (name) values ('Black-capped chickadee');
insert into race (name) values ('Burmese brown mountain tortoise');
insert into race (name) values ('Woylie');
insert into race (name) values ('Ibis, glossy');
insert into race (name) values ('Cardinal, black-throated');
insert into race (name) values ('Glider, feathertail');
insert into race (name) values ('Cattle egret');
insert into race (name) values ('Snowy sheathbill');
insert into race (name) values ('Squirrel, thirteen-lined');
insert into race (name) values ('African wild dog');
insert into race (name) values ('Cat, civet');
insert into race (name) values ('Malachite kingfisher');
insert into race (name) values ('Alligator, american');
insert into race (name) values ('Asian red fox');
insert into race (name) values ('Striped hyena');
insert into race (name) values ('Antelope ground squirrel');
insert into race (name) values ('Flycatcher, tyrant');
insert into race (name) values ('Vulture, bengal');
insert into race (name) values ('Macaque, bonnet');
insert into race (name) values ('Dingo');
insert into race (name) values ('Barrows goldeneye');
insert into race (name) values ('Booby, masked');
insert into race (name) values ('Dragon, ornate rock');
insert into race (name) values ('Asian elephant');
insert into race (name) values ('Roadrunner, greater');
insert into race (name) values ('Tammar wallaby');
insert into race (name) values ('Goose, canada');
insert into race (name) values ('Caracara (unidentified)');
insert into race (name) values ('Bettong, brush-tailed');
insert into race (name) values ('Corella, long-billed');
insert into race (name) values ('Penguin, magellanic');
insert into race (name) values ('Woodcock, american');
insert into race (name) values ('Blue and yellow macaw');
insert into race (name) values ('Neotropic cormorant');
insert into race (name) values ('Huron');
insert into race (name) values ('Sheep, stone');
insert into race (name) values ('Langur, hanuman');
insert into race (name) values ('Leopard');
insert into race (name) values ('Stick insect');
insert into race (name) values ('Arctic fox');
insert into race (name) values ('Grey mouse lemur');
insert into race (name) values ('Sable antelope');
insert into race (name) values ('Insect, stick');
insert into race (name) values ('Common eland');
insert into race (name) values ('Bare-faced go away bird');
insert into race (name) values ('Oribi');
insert into race (name) values ('Springhare');
insert into race (name) values ('Falcon, prairie');
insert into race (name) values ('Asiatic wild ass');
insert into race (name) values ('White-throated robin');
insert into race (name) values ('Stork, greater adjutant');
insert into race (name) values ('Brazilian otter');
insert into race (name) values ('Bustard, stanley');
insert into race (name) values ('Bleu, red-cheeked cordon');
insert into race (name) values ('Boubou, southern');
insert into race (name) values ('Green vine snake');
insert into race (name) values ('Boa, malagasy ground');
insert into race (name) values ('Cat, tiger');
insert into race (name) values ('Long-necked turtle');
insert into race (name) values ('Glossy starling (unidentified)');
insert into race (name) values ('African ground squirrel (unidentified)');
insert into race (name) values ('White-browed sparrow weaver');
insert into race (name) values ('Bat, little brown');
insert into race (name) values ('Brindled gnu');
insert into race (name) values ('Black spider monkey');
insert into race (name) values ('Wallaby, whip-tailed');
insert into race (name) values ('Gazer, sun');
insert into race (name) values ('Greylag goose');
insert into race (name) values ('Wolf, common');
insert into race (name) values ('Lilac-breasted roller');
insert into race (name) values ('Stork, openbill');
insert into race (name) values ('Penguin, galapagos');
insert into race (name) values ('Sloth, two-toed');
insert into race (name) values ('Vulture, oriental white-backed');
insert into race (name) values ('Duck, blue');
insert into race (name) values ('Common long-nosed armadillo');
insert into race (name) values ('Savannah deer (unidentified)');
insert into race (name) values ('Mynah, indian');
insert into race (name) values ('Capuchin, brown');
insert into race (name) values ('Rufous tree pie');
insert into race (name) values ('Owl, white-browed');
insert into race (name) values ('Striped skunk');
insert into race (name) values ('Golden-mantled ground squirrel');
insert into race (name) values ('Tiger snake');
insert into race (name) values ('Shelduck, common');
insert into race (name) values ('Eastern indigo snake');
insert into race (name) values ('Yellow-crowned night heron');
insert into race (name) values ('Dragonfly, russian');
insert into race (name) values ('Gazelle, thomson''s');
insert into race (name) values ('Sloth bear');
insert into race (name) values ('Rufous-collared sparrow');
insert into race (name) values ('Horned lark');
insert into race (name) values ('Coatimundi, white-nosed');
insert into race (name) values ('Levaillant''s barbet');
insert into race (name) values ('Deer, white-tailed');
insert into race (name) values ('Possum, western pygmy');
insert into race (name) values ('Carpet python');
insert into race (name) values ('Asian water buffalo');
insert into race (name) values ('Raven, cape');
insert into race (name) values ('Roan antelope');
insert into race (name) values ('Hyrax');
insert into race (name) values ('Otter, oriental short-clawed');
insert into race (name) values ('Goose, spur-winged');
insert into race (name) values ('Silver-backed fox');
insert into race (name) values ('Jaguar');
insert into race (name) values ('Cormorant, javanese');
insert into race (name) values ('American alligator');
insert into race (name) values ('Kori bustard');
insert into race (name) values ('Anteater, giant');
insert into race (name) values ('Jungle kangaroo');
insert into race (name) values ('African bush squirrel');
insert into race (name) values ('Mongoose, eastern dwarf');
insert into race (name) values ('Dog, bush');
insert into race (name) values ('Western bearded dragon');
insert into race (name) values ('Macaw, green-winged');
insert into race (name) values ('Bee-eater (unidentified)');
insert into race (name) values ('Squirrel, thirteen-lined');
insert into race (name) values ('Red-billed buffalo weaver');
insert into race (name) values ('Stork, european');
insert into race (name) values ('Arboral spiny rat');
insert into race (name) values ('Gecko (unidentified)');
insert into race (name) values ('Eurasian hoopoe');
insert into race (name) values ('Mouse, four-striped grass');
insert into race (name) values ('Barbet, black-collared');
insert into race (name) values ('Salmon pink bird eater tarantula');
insert into race (name) values ('Seven-banded armadillo');
insert into race (name) values ('African lynx');
insert into race (name) values ('Cat, kaffir');
insert into race (name) values ('Boa, columbian rainbow');
insert into race (name) values ('Ibis, glossy');
insert into race (name) values ('Vulture, egyptian');
insert into race (name) values ('Green vine snake');
insert into race (name) values ('Common wallaroo');
insert into race (name) values ('Spotted hyena');
insert into race (name) values ('Gray rhea');
insert into race (name) values ('Lion, african');
insert into race (name) values ('Echidna, short-beaked');
insert into race (name) values ('Bandicoot, short-nosed');
insert into race (name) values ('Flightless cormorant');
insert into race (name) values ('Jaguarundi');
insert into race (name) values ('Squirrel, red');
insert into race (name) values ('Dragon, komodo');
insert into race (name) values ('Southern black-backed gull');
insert into race (name) values ('Squirrel, malabar');
insert into race (name) values ('Russian dragonfly');
insert into race (name) values ('Kite, black');
insert into race (name) values ('Bushpig');
insert into race (name) values ('Tropical buckeye butterfly');
insert into race (name) values ('Woodchuck');
insert into race (name) values ('Shrew, mandras tree');
insert into race (name) values ('Goose, snow');
insert into race (name) values ('Black-eyed bulbul');
insert into race (name) values ('Red-winged blackbird');
insert into race (name) values ('Sambar');
insert into race (name) values ('Otter, brazilian');
insert into race (name) values ('Tsessebe');
insert into race (name) values ('Long-billed corella');
insert into race (name) values ('Indian red admiral');
insert into race (name) values ('Gecko, barking');
insert into race (name) values ('Civet, common palm');
insert into race (name) values ('Bandicoot, short-nosed');
insert into race (name) values ('Sugar glider');
insert into race (name) values ('Blue peacock');
insert into race (name) values ('Asian water dragon');
insert into race (name) values ('Curlew, black');
insert into race (name) values ('Long-tailed jaeger');
insert into race (name) values ('Green-winged macaw');
insert into race (name) values ('Flamingo, chilean');
insert into race (name) values ('Dove, mourning collared');
insert into race (name) values ('Black-crowned night heron');
insert into race (name) values ('Lizard (unidentified)');
insert into race (name) values ('Cat, ringtail');
insert into race (name) values ('Sun gazer');
insert into race (name) values ('Goldeneye, barrows');
insert into race (name) values ('Hummingbird (unidentified)');
insert into race (name) values ('Bat, asian false vampire');
insert into race (name) values ('Starling, red-shouldered glossy');
insert into race (name) values ('White-nosed coatimundi');
insert into race (name) values ('Red-tailed wambenger');
insert into race (name) values ('Lapwing, southern');
insert into race (name) values ('Flicker, campo');
insert into race (name) values ('Brown pelican');
insert into race (name) values ('Pigeon, feral rock');
insert into race (name) values ('Lion, south american sea');
insert into race (name) values ('Marmot, hoary');
insert into race (name) values ('Egyptian viper');
insert into race (name) values ('Brocket, red');
insert into race (name) values ('Pied kingfisher');
insert into race (name) values ('African bush squirrel');
insert into race (name) values ('Great egret');
insert into race (name) values ('Monkey, red howler');
insert into race (name) values ('Hyrax');
insert into race (name) values ('White-faced whistling duck');
insert into race (name) values ('Cardinal, red-capped');
insert into race (name) values ('Grey heron');
insert into race (name) values ('Openbill, asian');
insert into race (name) values ('Lemur, grey mouse');
insert into race (name) values ('Python (unidentified)');
insert into race (name) values ('Wallaby, bennett''s');
insert into race (name) values ('Python (unidentified)');
insert into race (name) values ('Bleu, red-cheeked cordon');
insert into race (name) values ('European red squirrel');
insert into race (name) values ('Pigeon, feral rock');
insert into race (name) values ('Deer, swamp');
insert into race (name) values ('Possum, golden brush-tailed');
insert into race (name) values ('Macaque, bonnet');
insert into race (name) values ('Netted rock dragon');
insert into race (name) values ('Flying fox (unidentified)');
insert into race (name) values ('Raccoon, crab-eating');
insert into race (name) values ('Wombat, common');
insert into race (name) values ('Eagle, pallas''s fish');
insert into race (name) values ('Little cormorant');
insert into race (name) values ('Komodo dragon');
insert into race (name) values ('Mexican wolf');
insert into race (name) values ('Ring-necked pheasant');
insert into race (name) values ('Red-breasted nuthatch');
insert into race (name) values ('Otter, canadian river');
insert into race (name) values ('American racer');
insert into race (name) values ('Great horned owl');
insert into race (name) values ('Great egret');
insert into race (name) values ('Mouse, four-striped grass');
insert into race (name) values ('Dolphin, bottle-nose');
insert into race (name) values ('Cliffchat, mocking');
insert into race (name) values ('Dove, little brown');
insert into race (name) values ('Chameleon (unidentified)');
insert into race (name) values ('Lorikeet, scaly-breasted');
insert into race (name) values ('Screamer, southern');
insert into race (name) values ('Black-collared barbet');
insert into race (name) values ('Wallaby, tammar');
insert into race (name) values ('Stork, white');
insert into race (name) values ('Goanna lizard');
insert into race (name) values ('Magpie, black-backed');
insert into race (name) values ('Tortoise, galapagos');
insert into race (name) values ('Woodchuck');
insert into race (name) values ('European wild cat');
insert into race (name) values ('Indian red admiral');
insert into race (name) values ('Long-billed cockatoo');
insert into race (name) values ('Eagle, crowned');
insert into race (name) values ('Sloth, two-toed');
insert into race (name) values ('Lion, african');
insert into race (name) values ('Blue wildebeest');
insert into race (name) values ('Barasingha deer');
insert into race (name) values ('Asian water dragon');
insert into race (name) values ('Cape wild cat');
insert into race (name) values ('Frilled lizard');
insert into race (name) values ('Miner''s cat');
insert into race (name) values ('Bush dog');
insert into race (name) values ('Trotter, lily');
insert into race (name) values ('Bonnet macaque');
insert into race (name) values ('Squirrel, palm');
insert into race (name) values ('Blue-tongued skink');
insert into race (name) values ('Eurasian badger');
insert into race (name) values ('Starling, superb');
insert into race (name) values ('Gull, swallow-tail');
insert into race (name) values ('Common wombat');
insert into race (name) values ('Monkey, black spider');
insert into race (name) values ('Two-toed sloth');
insert into race (name) values ('Pheasant, common');
insert into race (name) values ('Squirrel, palm');
insert into race (name) values ('Wolf spider');
insert into race (name) values ('Phascogale, red-tailed');
insert into race (name) values ('Kangaroo, eastern grey');
insert into race (name) values ('Pintail, white-cheeked');
insert into race (name) values ('Dunnart, fat-tailed');
insert into race (name) values ('Eagle, bateleur');
insert into race (name) values ('Cormorant, king');
insert into race (name) values ('Armadillo, seven-banded');
insert into race (name) values ('Sheep, stone');
insert into race (name) values ('Darwin ground finch (unidentified)');
insert into race (name) values ('Oryx, fringe-eared');
insert into race (name) values ('Great kiskadee');
insert into race (name) values ('Legaan, Monitor (unidentified)');
insert into race (name) values ('Salmon, sockeye');
insert into race (name) values ('Reedbuck, bohor');
insert into race (name) values ('Canadian tiger swallowtail butterfly');
insert into race (name) values ('Otter, north american river');
insert into race (name) values ('Common shelduck');
insert into race (name) values ('Squirrel, nelson ground');
insert into race (name) values ('Orca');
insert into race (name) values ('Bustard, denham''s');
insert into race (name) values ('Vulture, oriental white-backed');
insert into race (name) values ('Cormorant, flightless');
insert into race (name) values ('Robin, kalahari scrub');
insert into race (name) values ('Turtle (unidentified)');
insert into race (name) values ('Cape wild cat');
insert into race (name) values ('Frogmouth, tawny');
insert into race (name) values ('Vulture, oriental white-backed');
insert into race (name) values ('California sea lion');
insert into race (name) values ('Beaver, eurasian');
insert into race (name) values ('Sparrow, rufous-collared');
insert into race (name) values ('Long-crested hawk eagle');
insert into race (name) values ('Horned puffin');
insert into race (name) values ('Phascogale, brush-tailed');
insert into race (name) values ('Grey-footed squirrel');
insert into race (name) values ('Grizzly bear');
insert into race (name) values ('Heron, boat-billed');
insert into race (name) values ('Goose, greylag');
insert into race (name) values ('Gray duiker');
insert into race (name) values ('White-tailed jackrabbit');
insert into race (name) values ('Javan gold-spotted mongoose');
insert into race (name) values ('Sloth, pale-throated three-toed');
insert into race (name) values ('Bobcat');
insert into race (name) values ('Albatross, galapagos');
insert into race (name) values ('Fat-tailed dunnart');
insert into race (name) values ('Antelope, roan');
insert into race (name) values ('Long-necked turtle');
insert into race (name) values ('Galapagos tortoise');
insert into race (name) values ('Toddy cat');
insert into race (name) values ('Fox, grey');
insert into race (name) values ('White-winged tern');
insert into race (name) values ('Griffon vulture');
insert into race (name) values ('Brocket, red');
insert into race (name) values ('Bulbul, black-eyed');
insert into race (name) values ('Brazilian otter');
insert into race (name) values ('Crane, stanley');
insert into race (name) values ('Cat, kaffir');
insert into race (name) values ('Chacma baboon');
insert into race (name) values ('Eastern dwarf mongoose');
insert into race (name) values ('Griffon vulture');
insert into race (name) values ('Eagle, bald');
insert into race (name) values ('South American puma');
insert into race (name) values ('Common eland');
insert into race (name) values ('Macaw, blue and gold');
insert into race (name) values ('Greater blue-eared starling');
insert into race (name) values ('White-browed sparrow weaver');
insert into race (name) values ('Cockatoo, long-billed');
insert into race (name) values ('Bohor reedbuck');
insert into race (name) values ('Rhinoceros, white');
insert into race (name) values ('Australian masked owl');
insert into race (name) values ('Cougar');
insert into race (name) values ('Lizard, frilled');
insert into race (name) values ('Heron, black-crowned night');
insert into race (name) values ('Turkey, common');
insert into race (name) values ('Beisa oryx');
insert into race (name) values ('Crane, stanley');
insert into race (name) values ('Blue catfish');
insert into race (name) values ('Phalarope, northern');
insert into race (name) values ('Wallaby, river');
insert into race (name) values ('Sockeye salmon');
insert into race (name) values ('Bird, magnificent frigate');
insert into race (name) values ('Starling, red-shouldered glossy');
insert into race (name) values ('Lion, south american sea');
insert into race (name) values ('Rhea, greater');
insert into race (name) values ('Grey fox');
insert into race (name) values ('Western pygmy possum');
insert into race (name) values ('Avocet, pied');
insert into race (name) values ('Stork, marabou');
insert into race (name) values ('Northern fur seal');
insert into race (name) values ('Sable antelope');
insert into race (name) values ('Black spider monkey');
insert into race (name) values ('Western palm tanager (unidentified)');
insert into race (name) values ('Goose, andean');
insert into race (name) values ('Capuchin, brown');
insert into race (name) values ('Paddy heron (unidentified)');
insert into race (name) values ('Stork, marabou');
insert into race (name) values ('American beaver');
insert into race (name) values ('Roseat flamingo');
insert into race (name) values ('Monkey, vervet');
insert into race (name) values ('Brindled gnu');
insert into race (name) values ('White-fronted capuchin');
insert into race (name) values ('Pine snake (unidentified)');
insert into race (name) values ('Coot, red-knobbed');
insert into race (name) values ('Hartebeest, coke''s');
insert into race (name) values ('Black-crowned crane');
insert into race (name) values ('Springhare');
insert into race (name) values ('Black-capped capuchin');
insert into race (name) values ('Penguin, little blue');
insert into race (name) values ('Ostrich');
insert into race (name) values ('Wattled crane');
insert into race (name) values ('Bontebok');
insert into race (name) values ('Burmese brown mountain tortoise');
insert into race (name) values ('Sloth, two-toed');
insert into race (name) values ('Dragon, asian water');
insert into race (name) values ('Cottonmouth');
insert into race (name) values ('Argalis');
insert into race (name) values ('Warthog');
insert into race (name) values ('Black-tailed tree creeper');
insert into race (name) values ('Wattled crane');
insert into race (name) values ('Tortoise, desert');
insert into race (name) values ('Langur, gray');
insert into race (name) values ('Blue peacock');
insert into race (name) values ('Snowy sheathbill');
insert into race (name) values ('Golden-mantled ground squirrel');
insert into race (name) values ('Opossum, american virginia');
insert into race (name) values ('Long-tailed spotted cat');
insert into race (name) values ('Civet, small-toothed palm');
insert into race (name) values ('Lorikeet, scaly-breasted');
insert into race (name) values ('Bustard, denham''s');
insert into race (name) values ('Pademelon, red-legged');
insert into race (name) values ('Grey fox');
insert into race (name) values ('Eagle, bateleur');
insert into race (name) values ('Southern boubou');
insert into race (name) values ('Goose, snow');
insert into race (name) values ('Stone sheep');
insert into race (name) values ('White-throated toucan');
insert into race (name) values ('Falcon, peregrine');
insert into race (name) values ('Rhea, greater');
insert into race (name) values ('Ring dove');
insert into race (name) values ('Parrot, hawk-headed');
insert into race (name) values ('Wild water buffalo');
insert into race (name) values ('Cat, european wild');
insert into race (name) values ('Lynx, african');
insert into race (name) values ('Crane, brolga');
insert into race (name) values ('African wild cat');
insert into race (name) values ('Hawk, galapagos');
insert into race (name) values ('Magellanic penguin');
insert into race (name) values ('South American meadowlark (unidentified)');
insert into race (name) values ('Woodrat (unidentified)');
insert into race (name) values ('Tarantula');
insert into race (name) values ('Beaver, eurasian');
insert into race (name) values ('Gecko (unidentified)');
insert into race (name) values ('Blue-breasted cordon bleu');
insert into race (name) values ('Wolf spider');
insert into race (name) values ('Owl, snowy');
insert into race (name) values ('Seven-banded armadillo');
insert into race (name) values ('Owl, madagascar hawk');
insert into race (name) values ('Lappet-faced vulture');
insert into race (name) values ('Grizzly bear');
insert into race (name) values ('Cuis');
insert into race (name) values ('White-lipped peccary');
insert into race (name) values ('Rattlesnake, eastern diamondback');
insert into race (name) values ('Goliath heron');
insert into race (name) values ('Crake, african black');
insert into race (name) values ('Red-tailed phascogale');
insert into race (name) values ('Iguana, marine');
insert into race (name) values ('Seal, northern elephant');
insert into race (name) values ('Oriental short-clawed otter');
insert into race (name) values ('Warthog');
insert into race (name) values ('Klipspringer');
insert into race (name) values ('Red lava crab');
insert into race (name) values ('Sloth, two-toed');
insert into race (name) values ('Gull, silver');
insert into race (name) values ('White-fronted bee-eater');
insert into race (name) values ('Wildebeest, blue');
insert into race (name) values ('Galapagos tortoise');
insert into race (name) values ('Hottentot teal');
insert into race (name) values ('Porcupine, prehensile-tailed');
insert into race (name) values ('Cat, ringtail');
insert into race (name) values ('Galapagos mockingbird');
insert into race (name) values ('Antelope ground squirrel');
insert into race (name) values ('Rattlesnake, dusky');
insert into race (name) values ('Bengal vulture');
insert into race (name) values ('Small-spotted genet');
insert into race (name) values ('Macaw, blue and gold');
insert into race (name) values ('Buttermilk snake');
insert into race (name) values ('Openbill stork');
insert into race (name) values ('Crowned eagle');
insert into race (name) values ('Gecko, barking');
insert into race (name) values ('Black swan');
insert into race (name) values ('Otter, north american river');
insert into race (name) values ('Bush dog');
insert into race (name) values ('Lizard, frilled');
insert into race (name) values ('Bleu, blue-breasted cordon');
insert into race (name) values ('Vulture, white-rumped');
insert into race (name) values ('Southern screamer');
insert into race (name) values ('Sparrow, rufous-collared');
insert into race (name) values ('Ringtail');
insert into race (name) values ('Openbill, asian');
insert into race (name) values ('Indian tree pie');
insert into race (name) values ('Peacock, blue');
insert into race (name) values ('Kite, black');
insert into race (name) values ('Square-lipped rhinoceros');
insert into race (name) values ('Common wombat');
insert into race (name) values ('Gemsbok');
insert into race (name) values ('Common melba finch');
insert into race (name) values ('Black-backed magpie');
insert into race (name) values ('Cormorant, javanese');
insert into race (name) values ('Bleu, blue-breasted cordon');
insert into race (name) values ('Wallaby, whip-tailed');
insert into race (name) values ('Lion, south american sea');
insert into race (name) values ('Waterbuck, common');
insert into race (name) values ('Common nighthawk');
insert into race (name) values ('Stork, black-necked');
insert into race (name) values ('Indian red admiral');
insert into race (name) values ('Blackbird, red-winged');
insert into race (name) values ('Cape clawless otter');
insert into race (name) values ('Macaque, bonnet');
insert into race (name) values ('Malabar squirrel');
insert into race (name) values ('Bird, pied butcher');
insert into race (name) values ('Starling, greater blue-eared');
insert into race (name) values ('Cape wild cat');
insert into race (name) values ('Heron, gray');
insert into race (name) values ('Blackbird, red-winged');
insert into race (name) values ('Polecat, african');
insert into race (name) values ('Galapagos mockingbird');
insert into race (name) values ('Cockatoo, roseate');
insert into race (name) values ('Alligator, american');
insert into race (name) values ('Grey heron');
insert into race (name) values ('Glossy starling (unidentified)');
insert into race (name) values ('Western palm tanager (unidentified)');
insert into race (name) values ('Snake-necked turtle');
insert into race (name) values ('Screamer, crested');
insert into race (name) values ('Shrew, mandras tree');
insert into race (name) values ('Common nighthawk');
insert into race (name) values ('Cockatoo, sulfur-crested');
insert into race (name) values ('Teal, hottentot');
insert into race (name) values ('Pintail, white-cheeked');
insert into race (name) values ('Arctic hare');
insert into race (name) values ('Beaver, north american');
insert into race (name) values ('Ring-tailed lemur');
insert into race (name) values ('Pronghorn');
insert into race (name) values ('Baboon, yellow');
insert into race (name) values ('Crested screamer');
insert into race (name) values ('Golden brush-tailed possum');
insert into race (name) values ('Chipmunk, least');
insert into race (name) values ('Blue crane');
insert into race (name) values ('African red-eyed bulbul');
insert into race (name) values ('Sociable weaver');
insert into race (name) values ('Cockatoo, red-tailed');
insert into race (name) values ('Gull, kelp');
insert into race (name) values ('Feral rock pigeon');
insert into race (name) values ('Badger, european');
insert into race (name) values ('Cook''s tree boa');
insert into race (name) values ('Waterbuck, defassa');
insert into race (name) values ('Skua, great');
insert into race (name) values ('Pine siskin');
insert into race (name) values ('Black spider monkey');
insert into race (name) values ('Agouti');
insert into race (name) values ('Civet, common palm');
insert into race (name) values ('Ovenbird');
insert into race (name) values ('Crow, house');
insert into race (name) values ('Canadian tiger swallowtail butterfly');
insert into race (name) values ('Greater roadrunner');
insert into race (name) values ('European beaver');
insert into race (name) values ('Four-spotted skimmer');
insert into race (name) values ('Dabchick');
insert into race (name) values ('Macaw, blue and gold');
insert into race (name) values ('Bird, magnificent frigate');
insert into race (name) values ('Eastern indigo snake');
insert into race (name) values ('Asian false vampire bat');
insert into race (name) values ('Russian dragonfly');
insert into race (name) values ('Dromedary camel');
insert into race (name) values ('Palm squirrel');
insert into race (name) values ('Cat, toddy');
insert into race (name) values ('Cormorant, great');
insert into race (name) values ('Sheep, american bighorn');
insert into race (name) values ('Crested porcupine');
insert into race (name) values ('Zebra, common');
insert into race (name) values ('Egyptian vulture');
insert into race (name) values ('North American porcupine');
insert into race (name) values ('Marmot, yellow-bellied');
insert into race (name) values ('Hoary marmot');
insert into race (name) values ('Collared peccary');
insert into race (name) values ('Monkey, red howler');
insert into race (name) values ('Little cormorant');
insert into race (name) values ('Crake, african black');
insert into race (name) values ('Squirrel, eastern fox');
insert into race (name) values ('Pale-throated three-toed sloth');
insert into race (name) values ('Stork, yellow-billed');
insert into race (name) values ('Western palm tanager (unidentified)');
insert into race (name) values ('Southern hairy-nosed wombat');
insert into race (name) values ('Eastern cottontail rabbit');
insert into race (name) values ('Crow, american');
insert into race (name) values ('Collared lemming');
insert into race (name) values ('Eagle, crowned');
insert into race (name) values ('Sociable weaver');
insert into race (name) values ('Raven, cape');
insert into race (name) values ('Lizard, desert spiny');
insert into race (name) values ('Lorikeet, scaly-breasted');
insert into race (name) values ('Lapwing, southern');
insert into race (name) values ('Brown hyena');
insert into race (name) values ('Heron, boat-billed');
insert into race (name) values ('Bahama pintail');
insert into race (name) values ('Tammar wallaby');
insert into race (name) values ('Otter, giant');
insert into race (name) values ('Gazelle, grant''s');
insert into race (name) values ('Suricate');
insert into race (name) values ('Indian peacock');
insert into race (name) values ('Shrike, crimson-breasted');
insert into race (name) values ('Lion, california sea');
insert into race (name) values ('Devil, tasmanian');
insert into race (name) values ('Mexican boa');
insert into race (name) values ('Currasow (unidentified)');
insert into race (name) values ('California sea lion');
insert into race (name) values ('Shrew, mandras tree');
insert into race (name) values ('Sunbird, lesser double-collared');
insert into race (name) values ('Red-necked phalarope');
insert into race (name) values ('Snake, buttermilk');
insert into race (name) values ('Emerald green tree boa');
insert into race (name) values ('Goldeneye, common');
insert into race (name) values ('Cape raven');
insert into race (name) values ('Anaconda (unidentified)');
insert into race (name) values ('Ibis, sacred');
insert into race (name) values ('Squirrel, nelson ground');
insert into race (name) values ('Macaw, scarlet');
insert into race (name) values ('North American porcupine');
insert into race (name) values ('Bushbaby, large-eared');
insert into race (name) values ('Wallaby, dama');
insert into race (name) values ('Eastern box turtle');
insert into race (name) values ('Zorilla');
insert into race (name) values ('Platypus');
insert into race (name) values ('Heron, striated');
insert into race (name) values ('Gila monster');
insert into race (name) values ('Flycatcher, tyrant');
insert into race (name) values ('Red-legged pademelon');
insert into race (name) values ('Lemur, lesser mouse');
insert into race (name) values ('Argalis');
insert into race (name) values ('Canadian tiger swallowtail butterfly');
insert into race (name) values ('Tammar wallaby');
insert into race (name) values ('Land iguana');
insert into race (name) values ('Mountain lion');
insert into race (name) values ('Elephant, african');
insert into race (name) values ('Madagascar hawk owl');
insert into race (name) values ('Southern white-crowned shrike');
insert into race (name) values ('Lesser double-collared sunbird');
insert into race (name) values ('Cape white-eye');
insert into race (name) values ('Lizard, frilled');
insert into race (name) values ('Dove, mourning collared');
insert into race (name) values ('Hudsonian godwit');
insert into race (name) values ('Mourning collared dove');
insert into race (name) values ('Duiker, gray');
insert into race (name) values ('Arctic fox');
insert into race (name) values ('Cormorant, little');
insert into race (name) values ('Miner''s cat');
insert into race (name) values ('Great kiskadee');
insert into race (name) values ('Jackal, indian');
insert into race (name) values ('Zorro, azara''s');
insert into race (name) values ('Pelican, australian');
insert into race (name) values ('Beaver, eurasian');
insert into race (name) values ('Red deer');
insert into race (name) values ('Skink, blue-tongued');
insert into race (name) values ('Moose');
insert into race (name) values ('Albatross, waved');
insert into race (name) values ('Red and blue macaw');
insert into race (name) values ('Two-toed sloth');
insert into race (name) values ('Brush-tailed rat kangaroo');
insert into race (name) values ('Steenbok');
insert into race (name) values ('Vulture, turkey');
insert into race (name) values ('Beaver, american');
insert into race (name) values ('Crow, american');
insert into race (name) values ('Wolf, timber');
insert into race (name) values ('Otter, cape clawless');
insert into race (name) values ('Boar, wild');
insert into race (name) values ('Tortoise, desert');
insert into race (name) values ('Corella, long-billed');
insert into race (name) values ('Sally lightfoot crab');
insert into race (name) values ('Macaw, scarlet');
insert into race (name) values ('Red-cheeked cordon bleu');
insert into race (name) values ('African black crake');
insert into race (name) values ('Little brown bat');
insert into race (name) values ('Weaver, chestnut');
insert into race (name) values ('Horned puffin');
insert into race (name) values ('Swan, trumpeter');
insert into race (name) values ('Seal, common');
insert into race (name) values ('Gorilla, western lowland');
insert into race (name) values ('Neotropic cormorant');
insert into race (name) values ('Gemsbok');
insert into race (name) values ('Laughing dove');
insert into race (name) values ('White-mantled colobus');
insert into race (name) values ('Seal, northern elephant');
insert into race (name) values ('Yak');
insert into race (name) values ('Oryx, fringe-eared');
insert into race (name) values ('Peacock, blue');
insert into race (name) values ('Chacma baboon');
insert into race (name) values ('Reedbuck, bohor');
insert into race (name) values ('Weaver, sociable');
insert into race (name) values ('Parakeet, rose-ringed');
insert into race (name) values ('Deer, spotted');
insert into race (name) values ('Black rhinoceros');
insert into race (name) values ('Indian tree pie');
insert into race (name) values ('Cat, miner''s');
insert into race (name) values ('Zorro, azara''s');
insert into race (name) values ('Tailless tenrec');
insert into race (name) values ('Antechinus, brown');
insert into race (name) values ('Vulture, bengal');
insert into race (name) values ('Horned rattlesnake');
insert into race (name) values ('Sloth, hoffman''s');
insert into race (name) values ('Mocking cliffchat');
insert into race (name) values ('Macaque, rhesus');
insert into race (name) values ('Penguin, fairy');
insert into race (name) values ('Hornbill, red-billed');
insert into race (name) values ('Sheep, red');
insert into race (name) values ('Macaw, red and blue');
insert into race (name) values ('Bustard, stanley');
insert into race (name) values ('Jackal, black-backed');
insert into race (name) values ('Kingfisher, pied');
insert into race (name) values ('Harbor seal');
insert into race (name) values ('Little heron');
insert into race (name) values ('Anaconda (unidentified)');
insert into race (name) values ('Least chipmunk');
insert into race (name) values ('Savanna fox');
insert into race (name) values ('Three-banded plover');
insert into race (name) values ('South American sea lion');
insert into race (name) values ('Red brocket');
insert into race (name) values ('Fox, grey');
insert into race (name) values ('Turtle (unidentified)');
insert into race (name) values ('Otter, oriental short-clawed');
insert into race (name) values ('Topi');
insert into race (name) values ('Goose, andean');
insert into race (name) values ('White-winged tern');
insert into race (name) values ('Four-horned antelope');
insert into race (name) values ('Ibis, sacred');
insert into race (name) values ('Rhinoceros, square-lipped');
insert into race (name) values ('Flicker, campo');
insert into race (name) values ('Squirrel, smith''s bush');
insert into race (name) values ('Orca');
insert into race (name) values ('Lemur, ring-tailed');
insert into race (name) values ('Northern phalarope');
insert into race (name) values ('Heron, grey');
insert into race (name) values ('Grant''s gazelle');
insert into race (name) values ('Weaver, chestnut');
insert into race (name) values ('Siskin, yellow-rumped');
insert into race (name) values ('Monkey, rhesus');
insert into race (name) values ('Lemming, arctic');
insert into race (name) values ('Jackal, silver-backed');
insert into race (name) values ('Yellow-bellied marmot');
insert into race (name) values ('Heron, goliath');
insert into race (name) values ('Kingfisher, malachite');
insert into race (name) values ('White rhinoceros');
insert into race (name) values ('Red-shouldered glossy starling');
insert into race (name) values ('Bleu, red-cheeked cordon');
insert into race (name) values ('Lava gull');
insert into race (name) values ('Pelican, australian');
insert into race (name) values ('Lion, south american sea');
insert into race (name) values ('Wild turkey');
insert into race (name) values ('Red-winged hawk (unidentified)');
insert into race (name) values ('White-headed vulture');
insert into race (name) values ('Heron, striated');
insert into race (name) values ('Short-nosed bandicoot');
insert into race (name) values ('Arboral spiny rat');
insert into race (name) values ('Cottonmouth');
insert into race (name) values ('Impala');
insert into race (name) values ('Crow, pied');
insert into race (name) values ('Bird (unidentified)');
insert into race (name) values ('Cat, native');
insert into race (name) values ('Malleefowl');
insert into race (name) values ('Rhesus macaque');
insert into race (name) values ('Hawk-headed parrot');
insert into race (name) values ('Ovenbird');
insert into race (name) values ('Puna ibis');
insert into race (name) values ('Buffalo, african');
insert into race (name) values ('Turkey, australian brush');
insert into race (name) values ('Red-billed buffalo weaver');
insert into race (name) values ('Dark-winged trumpeter');
insert into race (name) values ('Magpie, australian');
insert into race (name) values ('Phalarope, red-necked');
insert into race (name) values ('Bustard, kori');
insert into race (name) values ('Collared lemming');
insert into race (name) values ('Racer, blue');
insert into race (name) values ('Buffalo, wild water');
insert into race (name) values ('Crane, wattled');
insert into race (name) values ('Zebra, plains');
insert into race (name) values ('Caribou');
insert into race (name) values ('Magnificent frigate bird');
insert into race (name) values ('Least chipmunk');
insert into race (name) values ('Eastern cottontail rabbit');
insert into race (name) values ('Racer snake');
insert into race (name) values ('Seal, northern fur');
insert into race (name) values ('Savanna fox');
insert into race (name) values ('Cliffchat, mocking');
insert into race (name) values ('Small-toothed palm civet');
insert into race (name) values ('Sally lightfoot crab');
insert into race (name) values ('African fish eagle');
insert into race (name) values ('White-faced whistling duck');
insert into race (name) values ('Western spotted skunk');
insert into race (name) values ('Magnificent frigate bird');
insert into race (name) values ('Cormorant, large');
insert into race (name) values ('Vulture, egyptian');
insert into race (name) values ('Caracara (unidentified)');
insert into race (name) values ('European wild cat');
insert into race (name) values ('Greater roadrunner');
insert into race (name) values ('Glossy ibis');
insert into race (name) values ('Brazilian tapir');
insert into race (name) values ('Eagle, pallas''s fish');
insert into race (name) values ('Bushbaby, large-eared');
insert into race (name) values ('Eastern indigo snake');
insert into race (name) values ('Common rhea');
insert into race (name) values ('African ground squirrel (unidentified)');
insert into race (name) values ('Asian water buffalo');
insert into race (name) values ('Little grebe');
insert into race (name) values ('Kafue flats lechwe');
insert into race (name) values ('Hanuman langur');
insert into race (name) values ('Gila monster');
insert into race (name) values ('Spider, wolf');
insert into race (name) values ('Golden brush-tailed possum');
insert into race (name) values ('Creeper, black-tailed tree');
insert into race (name) values ('Penguin, little blue');
insert into race (name) values ('Nilgai');
insert into race (name) values ('Greater roadrunner');
insert into race (name) values ('Ring dove');
insert into race (name) values ('Green-backed heron');
insert into race (name) values ('Black-faced kangaroo');
insert into race (name) values ('Lesser masked weaver');
insert into race (name) values ('Antelope ground squirrel');
insert into race (name) values ('Black rhinoceros');
insert into race (name) values ('Purple moorhen');
insert into race (name) values ('Otter, north american river');
insert into race (name) values ('Bleu, red-cheeked cordon');
insert into race (name) values ('Macaw, blue and gold');
insert into race (name) values ('Armadillo, nine-banded');
insert into race (name) values ('Jackal, golden');
insert into race (name) values ('Chestnut weaver');
insert into race (name) values ('Grey-footed squirrel');
insert into race (name) values ('Crane, sandhill');
insert into race (name) values ('Red-legged pademelon');
insert into race (name) values ('Blue-footed booby');
insert into race (name) values ('Arctic hare');
insert into race (name) values ('Bottle-nose dolphin');
insert into race (name) values ('Capuchin, black-capped');
insert into race (name) values ('Black-tailed tree creeper');
insert into race (name) values ('Slender loris');
insert into race (name) values ('Boat-billed heron');
insert into race (name) values ('Stilt, black-winged');
insert into race (name) values ('Weaver, lesser masked');
insert into race (name) values ('Swan, trumpeter');
insert into race (name) values ('Dragon, ornate rock');
insert into race (name) values ('Eurasian badger');
insert into race (name) values ('Possum, common brushtail');
insert into race (name) values ('Reedbuck, bohor');
insert into race (name) values ('Glossy starling (unidentified)');
insert into race (name) values ('Olive baboon');
insert into race (name) values ('Red-necked wallaby');
insert into race (name) values ('Yellow-billed hornbill');
insert into race (name) values ('Hyena, brown');
insert into race (name) values ('Small-clawed otter');
insert into race (name) values ('Black bear');
insert into race (name) values ('Pampa gray fox');
insert into race (name) values ('Fox, cape');
insert into race (name) values ('Banded mongoose');
insert into race (name) values ('Admiral, indian red');
insert into race (name) values ('Magistrate black colobus');
insert into race (name) values ('Timber wolf');
insert into race (name) values ('Shrike, crimson-breasted');
insert into race (name) values ('Cobra (unidentified)');
insert into race (name) values ('Bent-toed gecko');
insert into race (name) values ('Loris, slender');
insert into race (name) values ('Beaver, european');
insert into race (name) values ('Zebra, common');
insert into race (name) values ('Mongoose, eastern dwarf');
insert into race (name) values ('Common pheasant');
insert into race (name) values ('Feral rock pigeon');
insert into race (name) values ('Sheep, red');
insert into race (name) values ('Lemur, lesser mouse');
insert into race (name) values ('Asian lion');
insert into race (name) values ('Turkey, australian brush');
insert into race (name) values ('Duck, blue');
insert into race (name) values ('Sugar glider');
insert into race (name) values ('Ibis, puna');
insert into race (name) values ('Kangaroo, jungle');
insert into race (name) values ('Verreaux''s sifaka');
insert into race (name) values ('Loris, slender');
insert into race (name) values ('Otter, giant');
insert into race (name) values ('Nutcracker, clark''s');
insert into race (name) values ('Indian giant squirrel');
insert into race (name) values ('Cockatoo, red-tailed');
insert into race (name) values ('Glider, feathertail');
insert into race (name) values ('Bird, secretary');
insert into race (name) values ('Pacific gull');
insert into race (name) values ('Common brushtail possum');
insert into race (name) values ('Common zebra');
insert into race (name) values ('Dabchick');
insert into race (name) values ('Alligator, mississippi');
insert into race (name) values ('American buffalo');
insert into race (name) values ('Quail, gambel''s');
insert into race (name) values ('Australian spiny anteater');
insert into race (name) values ('Pied kingfisher');
insert into race (name) values ('American badger');
insert into race (name) values ('Red lava crab');
insert into race (name) values ('Common grenadier');
insert into race (name) values ('Black-collared barbet');
insert into race (name) values ('Dove, little brown');
insert into race (name) values ('Brolga crane');
insert into race (name) values ('Golden brush-tailed possum');
insert into race (name) values ('Square-lipped rhinoceros');
insert into race (name) values ('Pie, rufous tree');
insert into race (name) values ('Crested barbet');
insert into race (name) values ('Crowned eagle');
insert into race (name) values ('Caracara (unidentified)');
insert into race (name) values ('Three-banded plover');
insert into race (name) values ('Eagle, golden');
insert into race (name) values ('Brown pelican');
insert into race (name) values ('Masked booby');
insert into race (name) values ('Galah');
insert into race (name) values ('Camel, dromedary');
insert into race (name) values ('Loris, slender');
insert into race (name) values ('Macaw, blue and gold');
insert into race (name) values ('Miner''s cat');
insert into race (name) values ('Sage grouse');
insert into race (name) values ('Opossum, american virginia');
insert into race (name) values ('Crab-eating fox');
insert into race (name) values ('Monkey, bleeding heart');
insert into race (name) values ('Roseat flamingo');
insert into race (name) values ('Eagle owl (unidentified)');
insert into race (name) values ('Squirrel, nelson ground');
insert into race (name) values ('Black bear');
insert into race (name) values ('Urial');
insert into race (name) values ('Northern fur seal');
insert into race (name) values ('Deer, white-tailed');
insert into race (name) values ('Eastern quoll');
insert into race (name) values ('Spotted wood sandpiper');
insert into race (name) values ('Quoll, spotted-tailed');
insert into race (name) values ('African snake (unidentified)');
insert into race (name) values ('Lemur, brown');
insert into race (name) values ('Jaeger, long-tailed');
insert into race (name) values ('Dove, laughing');
insert into race (name) values ('Savanna baboon');
insert into race (name) values ('Purple grenadier');
insert into race (name) values ('Hawk-eagle, crowned');
insert into race (name) values ('Swallow-tail gull');
insert into race (name) values ('Brazilian otter');
insert into race (name) values ('Sloth bear');
insert into race (name) values ('Musk ox');
insert into race (name) values ('Turtle (unidentified)');
insert into race (name) values ('Rat, desert kangaroo');
insert into race (name) values ('Onager');
insert into race (name) values ('Sambar');
insert into race (name) values ('Cat, ringtail');
insert into race (name) values ('White rhinoceros');
insert into race (name) values ('Brindled gnu');
insert into race (name) values ('Harbor seal');
insert into race (name) values ('Hyrax');
insert into race (name) values ('Fork-tailed drongo');
insert into race (name) values ('American bighorn sheep');
insert into race (name) values ('Brown brocket');
insert into race (name) values ('Giraffe');
insert into race (name) values ('Stork, yellow-billed');
insert into race (name) values ('Pied crow');
insert into race (name) values ('Cat, ringtail');
insert into race (name) values ('Flightless cormorant');
insert into race (name) values ('Polecat, african');
insert into race (name) values ('Red phalarope');
insert into race (name) values ('Otter, oriental short-clawed');
insert into race (name) values ('Great kiskadee');
insert into race (name) values ('Tortoise, burmese brown mountain');
insert into race (name) values ('European shelduck');
insert into race (name) values ('Neotropic cormorant');
insert into race (name) values ('Dove, laughing');
insert into race (name) values ('Tawny frogmouth');
insert into race (name) values ('Laughing dove');
insert into race (name) values ('Black-tailed deer');
insert into race (name) values ('Mandras tree shrew');
insert into race (name) values ('Fox, north american red');
insert into race (name) values ('Jackal, golden');
insert into race (name) values ('Frog (unidentified)');
insert into race (name) values ('Plover, three-banded');
insert into race (name) values ('Quail, gambel''s');
