USE HosPetAll;

INSERT INTO AUTHORITY(authority) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITY(authority) VALUES ('ROLE_RECEPTIONIST');
INSERT INTO AUTHORITY(authority) VALUES ('ROLE_WORKER');
INSERT INTO AUTHORITY(authority) VALUES ('ROLE_VETERINARIAN');
INSERT INTO AUTHORITY(authority) VALUES ('ROLE_CLIENT');
INSERT INTO AUTHORITY(authority) VALUES ('ROLE_NURSE');
